apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-app
  labels:
    app: sandbox-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandbox-app
  template:
    metadata:
      labels:
        app: sandbox-app
    spec:
      containers:
        - name: sandbox-app
          image: nexus.yuri.dev.br/sandbox-app:25
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: nexus-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-app
spec:
  selector:
    app: sandbox-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: "sandbox.yuri.dev.br"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: sandbox-app
                port:
                  number: 5000
