pipeline {
    agent docker
        docker {
            image 'docker:latest' 
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    stages {
        stage('Run shell') {
            steps {
                script {
                    sh 'docker'
                }
            }
        }
    }
}