pipeline {
    agent {
        label 'docker-agent'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker --version'
                    dockerapp = docker.build("nexus.yuri.dev.br/sandbox-app:${env.BUILD_ID}", "-f infra/Dockerfile .")
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    docker.withRegistry('https://nexus.yuri.dev.br', 'e9a997ff-2f07-45c2-84f3-a1b4320a5bbf') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
    }
}