pipeline {
    agent any

    stages {
        stage('Run shell') {
            steps {
                script {
                    // Define o template do pod
                    podTemplate(name: 'dind', label: 'dind') {
                        node('dind') {
                            // Executa os comandos dentro do contêiner Docker
                            container('dind') {
                                sh 'docker'
                            }
                        }
                    }
                }
            }
        }
    }
}